Updated NewBill Activity UI
Synergise-IIT-Bhubaneswar/QuickBills pull request #7
Opened 2021-10-27 00:39 UTC by Shashwat545

## Summary - New Feature/Bug Resolution
Updated the NewBill Activity UI so as to prevent the overlapping of TextViews and implemented a function which preprocesses the amount and displays it in exponential form if it is too large.

## Root Cause
The amount text was not being preprocessed and was being displaying as it was.

## Details
- The width of the Textviews is now restricted to 170 dp. <br>
- The amount text is now being preprocessed and if it is more than 8 digits then it is displayed in exponential form.
- Attached a screenshot for reference below
![Screenshot QuickBills](https://user-images.githubusercontent.com/78429106/138980387-3f4e1ed3-d8f4-4d20-bef0-f5d26bb7511d.jpeg)

## Checklist
- [x] I've read the [Contribution Guidelines](/CONTRIBUTING.md).
- [x] I've tested that the application is performing well and there is no breaking changes.

## Related Issues / Pull Requests
- Resolves #1

2021-10-27 12:34 UTC, sushant-iit requested changes
There are few modifcations which I want you to consider:
1. The logic behind preprocessing should go in preprocessing function. By this I mean:
![if else](https://user-images.githubusercontent.com/59964272/139065481-44d7cb0b-5b73-4cd4-9511-3c4cd07911da.JPG)
This if else block should go to preprocess function, if there is no change just return original value, that's it. This will enable the function to be reused anywhere.
2. Don't hardcode rupee symbol by removing line number 193 from NewBill Activity. This might face difficulty in some devices. Rather use that getString(R.string.rupee, totalAmount) functinon to get rupee symbol. 
3. Merge your changes as a single commit rather than three commits.
Thanks

2021-10-27 12:42 UTC, sushant-iit commented on app/src/main/java/com/sushant/quickbills/activity/NewBillActivity.kt
> +                if(totalAmount>99999999)
Put this in preprocess Function

2021-10-27 12:42 UTC, sushant-iit commented on app/src/main/java/com/sushant/quickbills/utils/preprocessDisplayText.kt
> +    val anss=str.substring(0,1)+"."+str.substring(1,3)+"E"+(str.length-1).toBigDecimal().toPlainString()
Add if else logic here..

2021-10-27 21:18 UTC, Shashwat545 commented
> There are few modifcations which I want you to consider:
> 
> 1. The logic behind preprocessing should go in preprocessing function. By this I mean:
>    ![if else](https://user-images.githubusercontent.com/59964272/139065481-44d7cb0b-5b73-4cd4-9511-3c4cd07911da.JPG)
>    This if else block should go to preprocess function, if there is no change just return original value, that's it. This will enable the function to be reused anywhere.
> 2. Don't hardcode rupee symbol by removing line number 193 from NewBill Activity. This might face difficulty in some devices. Rather use that getString(R.string.rupee, totalAmount) functinon to get rupee symbol.
> 3. Merge your changes as a single commit rather than three commits.
>    Thanks

@sushant-iit I have made the required modifications. Please check if it is fine now or any further changes are needed to be done.

2021-10-28 02:39 UTC, sushant-iit requested changes
And, please remove so many commits from your branch. You should have only one commit. It does not make sense to have 4 commits for this simple issue.

2021-10-28 02:39 UTC, sushant-iit commented on app/src/main/java/com/sushant/quickbills/activity/NewBillActivity.kt
> +                bill_amount.text=(getString(R.string.rupee_symbol_only)+" "+ans)
ans variable feels unnecessary here:
Make it like this 
bill_amount.text=(getString(R.string.rupee_symbol_only)+" "+preprocessDisplayText(totalAmount))

2021-10-28 02:39 UTC, sushant-iit commented on app/src/main/java/com/sushant/quickbills/utils/preprocessDisplayText.kt
> +    val anss=str.substring(0,1)+"."+str.substring(1,3)+"E"+(str.length-1).toBigDecimal().toPlainString()
Give anss a reasonable name like preprocessedText or something

2021-10-28 22:12 UTC, Shashwat545 commented
Please check now if anything else is to be done

2021-10-29 02:46 UTC, sushant-iit approved these changes
#merged

2021-10-29 02:46 UTC, merged

2021-10-29 04:54 UTC, rahulpathak-github commented
@sushant-iit Please add the difficulty tag too.

2021-11-05 06:18 UTC, sushant-iit commented
@rahulpathak-github @Shashwat545 Done